image: rufusmbugua/laravel-5

stages:
  - test
  - deploy

services:
- name: mysql:latest
  alias: mysql

test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - ./vendor/bin/phpunit

deploy:
  stage: deploy
  script: 
    - ./deployment/deploy-staging.sh

  before_script:
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    #- git config --global user.email "user@example.com"
    #- git config --global user.name "User name"

