stages:
  - test
  - deploy

services:
- name: mysql:latest
  alias: mysql

test:
  stage: test
  image: rufusmbugua/laravel-5
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - ./vendor/bin/phpunit

deploy:
  stage: deploy
  image: tetraweb/php:7.0    
  script: 
    - ./deployment/deploy-staging.sh

  before_script:
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
            
    environment:
        - name: production

