stages:
  - test
  - deploy

services:
- name: mysql:latest
  alias: mysql

test:
  stage: test
  image: rufusmbugua/laravel-5
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - ./vendor/bin/phpunit

deploy:
  stage: deploy
  environment:
    - name: production
  image: tetraweb/php:7.0    
  script: 
    - ./deployment/deploy-staging.sh

  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
            
    