language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install:
  - composer install
  - npm install
after_script:
  - cp .env.example .env
  - php artisan key:generate
