version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pod
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - default
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8070:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
  # php
  app:
    depends_on:
      - db
    build: .
    volumes:
      - .:/var/www/
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - default
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    networks:
      - default
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
networks:
  default:
volumes:
  db_data:
    driver: local
