version: '2'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    image: rufusmbugua/laravel-5
    ports:
    - 1080:80
    volumes:
    - /var/www/pod:/var/www/html
    depends_on:
    - db